version: "3.3"
services:
  sample-xxx:
    build:
      context: .
      dockerfile: Dockerfile
    image: sample-iXXX1
    init: true
    container_name: sample-cXXX1
    hostname: sampleX
    stdin_open: true
    tty: true
    # user: yamanaka試しにテスト 2021/04/03 →中止

